server:
  port: 8080
spring:
  application:
    name: Flow_manager
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 123
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: redis-server
      port: 6379
      password: redis

  cache:
    type: redis
    redis:
      time-to-live: 2000000
      cache-null-values: false

minio:
  user: userminio
  password: minio123
  port: 9000
  host: minio
  buckets:
    pdf-bucket: "pdf-bucket"
    non-pdf-bucket: "non-pdf-bucket"

kafka:
  server: kafka:9092
  group_id: file_path
  topics:
    pdf-converter-topic: pdf-converter-topic
    success-converter-topic: success-converter-topic
    error-converter-topic: error-converter-topic
    subscribe-expired-topic: subscribe-expired-topic
    subscribe-paid-topic: subscribe-paid-topic

subscribe:
  url: http://subscribe:8087

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        connectTimeout: 5000
        readTimeout: 10000

file-size:
  paid: 100
  free: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: Flow_manager
    export:
      prometheus:
        enabled: true