CREATE TABLE file_record (
  id BIGSERIAL PRIMARY KEY,
  file_path VARCHAR(128) NOT NULL,
  status VARCHAR(16) DEFAULT 'IN_PROGRESS',

  CONSTRAINT chk_file_status CHECK (status IN ('SUCCESS','IN_PROGRESS','ERROR','UPLOADED'))
);

CREATE TABLE outbox_event (
    id BIGSERIAL PRIMARY KEY,
    payload JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    outbox_type VARCHAR(20)
);